### ISSUE TITLE
editor-color turn white when using Legacy Gerry Oceanic

### ISSUE THREAD

**Issue by Qwenjin** [gerryhjs/gerry-themes#40] opened 2024-08-23 03:03 UTC
plugin version: 2024.1.0822 

idea version: IntelliJ IDEA 2024.1.6 (Ultimate Edition)
Build #IU-241.19072.14, built on August 8, 2024

**Comment by Qwenjin** [comment] 2024-08-23 03:05
plugin version: 2024.1.0822 

idea version: IntelliJ IDEA 2024.1.6 (Ultimate Edition)
Build #IU-241.19072.14, built on August 8, 2024

**Comment by gerryhjs** [comment] 2024-08-23 04:03
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8
This is an issue caused by IDE, it may apply an incompatible color scheme in some cases ([IDEA-325237](https://youtrack.jetbrains.com/issue/IDEA-325237)).
Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme, the issue should be solved.
For example: If you are using "Gerry Darcula" or "Legacy Gerry Darcula", then switch color scheme to "Gerry Darcula".

**Comment by gerryhjs** [comment] 2024-08-23 04:07
Duplicate to https://github.com/gerryhjs/gerry-themes/issues/8
This is an issue caused by IDE, it may apply an incompatible color scheme in some cases such as ([IDEA-325237](https://youtrack.jetbrains.com/issue/IDEA-325237)).
Please check the Settings | Editor | Color Scheme window and select the corresponding color scheme. It will be marked as "Theme Default" when using IDE 2024.1+.
For example: If you are using "Gerry Darcula" or "Legacy Gerry Darcula", then switch color scheme to "Gerry Darcula".

**Closed** 2024-08-26 02:56 UTC
